language: php

php:
 - 7.0
 - nightly

maxtrix:
  allow_failures:
   - php: nightly
  fast_finish: true

services:
 - redis-server

cache:
  directories:
    - $HOME/.composer/cache

install:
 - phpenv config-rm xdebug.ini
 - composer self-update
 - composer config --global discard-changes true
 - composer require satooshi/php-coveralls dev-master --dev
 - composer show --installed

script:
 - find -name "*.php" -not -path "./vendor/*" -print0 | xargs -n 1 -0 php -l
 - $(php -r 'if (PHP_MAJOR_VERSION >= 7) echo "phpdbg -qrr"; else echo "php";') vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
 - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
 - php vendor/bin/coveralls -v